global: 
  scrape_interval: 5s
scrape_configs: 
  - job_name: prometheus
    static_configs: 
    - targets: 
      - "localhost:9090"
  - job_name: node-exporter
    static_configs:
    - targets:
      # Change this list to ip/dns name of the node-exporter host
      - "host.docker.internal:9100"
